### ISSUE TITLE
CTD with SpectreCoils in 1.3.2

### ISSUE THREAD

**Issue by lhw** [AllTheMods/ATM3-Remix#218] opened 2019-07-06 16:17 UTC
Random crash to desktop when playing. Even nowhere near any of the spectre coils i'm actually using. Having them in sight or not doesn't seem to change the behaviour.

## Expected Behavior

Doesn't crash

## Current Behavior

It crashes randomly

## Steps to Reproduce

1. Place spectre coils
2. Stand motionless on a rooftop
3. Crash to desktop

## Log

[Full Log](https://gist.github.com/lhw/76ed7a3042add54214d6c7bd1b44c6b2)
```log
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at lumien.randomthings.tileentity.TileEntitySpectreCoil.hasCapability(TileEntitySpectreCoil.java:65)
	at p455w0rdslib.capabilities.CapabilityLightEmitter.hasCap(CapabilityLightEmitter.java:47)
	at p455w0rdslib.api.client.shader.LightHandler.update(LightHandler.java:152)
	at p455w0rdslib.asm.Hooks.enableColoredLighting(Hooks.java:26)
	at net.minecraft.client.renderer.RenderGlobal.func_174982_a(RenderGlobal.java:1133)
	at net.minecraft.client.renderer.RenderGlobal.func_174977_a(RenderGlobal.java:1125)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1328)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

```

## Detailed Description

Unless I remove all the spectre coils from all my dimensions this crash keeps happening. This error did not appear in 1.3.0. It's most likely a broken interaction between the passwordslib and randomthings.

**Comment by Yamza** [comment] 2019-07-06 16:23
Should report this on their page as well.

**Comment by Yamza** [comment] 2019-07-13 14:03
I am not able to reproduce this.

**Comment by lhw** [comment] 2019-07-13 16:57
It's indeed a bit harder to reproduce then I initially thought. I was trying to come with a PR for randomthings to fix this issue but I cannot reproduce this 100% of the time.
There was a comment on how to disable this issue on the client but that doesn't really fix the issue: https://github.com/lumien231/Random-Things/issues/426#issuecomment-509037090

**Comment by Darkere** [comment] 2019-07-13 17:18
Passwordlib will remove its shaders with a future update so there is little point in fixing it.

**Comment by lhw** [comment] 2019-07-13 18:58
So the solution for now would be to switch of the rendering part of passwordlib? I mean i'm fine with that. Its not really a required part.

**Comment by Yoosk** [comment] 2019-07-21 15:39
fixed by https://github.com/AllTheMods/ATM3-Remix/commit/05277cccec3eab8276d684dcc06779fa33113b22

**Closed by Yoosk** 2019-07-21 15:39 UTC
Labels: forge/mod issue
