### ISSUE TITLE
ATM3:R 1.0.1 AE" cable facade crash

### ISSUE THREAD

**Issue by belgariondunkelseele** [AllTheMods/ATM3-Remix#93] opened 2018-11-14 19:11 UTC
## Expected Behavior
One should be able to craft and use AE2 Cobblestone Cable Facade

## Current Behavior
Game Crashes after Crafting AE2 Cobblestone covers, even beffore selecting them on hotbar, happened to me and the other guy we have a server with

## Possible Solution
I certainly do not know... here, have our crash report :)
https://pastebin.com/bBPNAVWY 

edit: possibility: cable anchor is not shown in Jei, but craftable, might this be a problem?

## Steps to Reproduce

1.Craft AE2 cable facades in crafting grid
2.Close crafting grid
3.Watch it crash
4.

## Log
https://pastebin.com/bBPNAVWY

**Comment by derrickmehaffy** [comment] 2018-11-15 06:14
+1 can confirm this happened to a few players on my server as well. will try and get logs if I can.

**Comment by SecretFox** [comment] 2018-11-15 07:20
It's due to the advancement you get from crafting them the first time.  
You will also crash if you try to view advancements for Applied Energistics

**Comment by belgariondunkelseele** [comment] 2018-11-15 08:43
Well, looking at the Advancements did not Crash my client (yet) but did crash my friend's.

**Comment by martmists** [comment] 2018-11-15 13:21
Is anyone able to test with different RAM settings (from 6G up to 10G)?
If this is a RAM-related issue using more/less RAM should change the situation and give us a clue what happened. 

Anyone else commenting on this, please provide specs (CPU, GPU, Allocated RAM) and whether it worked for you or not. This way we are able to get an idea of what could cause it on hardware and/or potentially software level.

**Comment by Yamza** [comment] 2018-11-15 14:11
Confirmed that the cable anchor is not in JEI for some reason, however I was able to make the cobblestone facade on the official server without issue. I was also able to craft the facade in single player without issue.

Please provide the latest log from both client and server when this issue occurs, as well as the crash report.

**Comment by SecretFox** [comment] 2018-11-15 18:29
i7-4770K
GTX 1080 Ti
16GB RAM

Tested in SP with creative superflat worlds, and fresh install (all settings completely untouched).

6 GB https://gist.github.com/SecretFox/1952f14549f1f420d7b39158573ec0fe crash
8 GB https://gist.github.com/SecretFox/e3fd8c5706da6b729f720099eb4fd50f crash
10GB https://gist.github.com/SecretFox/34b8d60c98cbc08d8d685d841b00908c crash
Log for 10GB crash https://gist.github.com/SecretFox/586b92c17fbda36720d873a9d717b420

Crash happens as soon as i cheat facade from JEI and get the advancement. 
On server only client crashes, server will keep running (can't get logs atm though).

After relaunching the game i can craft facades just fine, but opening AE2 advancements crashes the game.

**Comment by Yamza** [comment] 2018-11-15 18:34
@SecretFox 
You've got an old java being used. I'm not confident that'll resolve the issue but it'd be a good first step to correct that and retest. https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/

`	Java Version: 1.8.0_51, Oracle Corporation`

**Comment by Yamza** [comment] 2018-11-15 18:50
Actually there appears to be a similar report in AE2 already regarding this: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3810

**Comment by SecretFox** [comment] 2018-11-15 19:48
Apparently it defaulted back to 0_51 after the 6GB test.

Yep,that seems to be it, removing blockcraftery and Elulib fixes it.
Updating to mysticallib-1.12.2-1.0.0.jar and blockcraftery-1.12.2-1.1.0.jar does not.

**Comment by belgariondunkelseele** [comment] 2018-11-15 21:21
this sounds interesting... for us, the only way to go back online again was deleting the facades from our player inventorys through the server console.

**Comment by martmists** [comment] 2018-11-16 07:02
Closing as there's an AE2 issue made for this

**Closed by martmists** 2018-11-16 07:02 UTC

**Comment by krisjenner** [comment] 2018-11-28 02:32
same crash only with Forge Multipart stone cover

[crash report](https://gist.github.com/krisjenner/deb3f1de3f77edd5fa518516fc7eb13a)
