### ISSUE TITLE
Identical recipies in ATM 3 6.0 Remix

### ISSUE THREAD

**Issue by Minyguy** [AllTheMods/ATM3-Remix#12] opened 2018-09-04 10:50 UTC
## Expected Behavior
The Wands from MineColonies and Better Builder's wands should have different recipies

## Current Behavior
the "Stone wand" from "Better Builder's Wands"s recipie is identical to "Building Tool" from "MineColonies", and the "Iron wand" from "Better Builder's Wands"' recipie is identical to "Scan Tool" from "MineColonies". MineColonies takes precedence, rendering the Better Builder's wands unobtainable, with the exception of diamond and unbreakable.

## Possible Solution
Change the recipies to something else.

## Steps to Reproduce
Attempt to craft Iron wand/Stone Wand from "Better Builder's Wands"

**Comment by Lartza** [comment] 2018-09-04 10:59
Duplicate of https://github.com/AllTheMods/ATM3-Remix/issues/8

**Closed** 2018-09-04 11:01 UTC
Labels: duplicate
