### ISSUE TITLE
Client crash when trying to search in jei

### ISSUE THREAD

**Issue by MythixDino** [AllTheMods/ATM3-Remix#56] opened 2018-09-24 11:57 UTC
## Expected Behavior
Client shouldn't crash when searching for something in jei.

## Current Behavior
Client crashes.

## Steps to Reproduce
1. Search something in jei. Usually happens when I search something starting with s*

## Log
https://gist.github.com/MythixDino/576ea1b6d5a64198cfb8faa957f16409

**Comment by Yamza** [comment] 2018-09-24 11:58
Do you have your settings as detailed here: https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/

**Comment by derrickmehaffy** [comment] 2018-09-24 12:43
Also cannot duplicate the issue @MythixDino can you please provide more information on your environment and settings. (IE OS, app you used to install the pack, allocated ram, CPU model, ect)

**Comment by DKnightADRI** [comment] 2018-09-24 12:49
A lot of this information can be found in the log, I'm having these issues as well sometimes. I have 16G allocated (needed for texture pack), i5 8600k @ 4GHz using Twitch Launcher.

**Comment by Yamza** [comment] 2018-09-24 12:52
```-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5812268544 bytes (5543 MB) / 17840996352 bytes (17014 MB) up to 17840996352 bytes (17014 MB)
	JVM Flags: 4 total; -XX:+AggressiveOpts -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms14336m -Xmx17408m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.4.2760 Optifine OptiFine_1.12.2_HD_U_E2 307 mods loaded, 307 mods active```
RAM set is double recommended.
Is that an AMD GPU? That might explain the issue.

**Comment by derrickmehaffy** [comment] 2018-09-24 13:01
@Yamza I use an AMD GPU on Linux and haven't noticed any issues. :man_shrugging:

**Comment by derrickmehaffy** [comment] 2018-09-24 13:03
Looks like OP is using Nvidia:
```
	OpenGlVersion: 4.6.0 NVIDIA 397.64
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
```

**Comment by Aezex** [comment] 2018-10-02 16:39
Here is another log: https://gist.github.com/Aezex/cae4b54ba120e3ed0e1162bfd703cb3d

Seems to be any crated item rendering in JEI.

**Comment by DKnightADRI** [comment] 2018-10-07 09:42
"After updating Java the error seems to have gone away."

How is this helpful if OP had the most recent java 8 version 13 days ago?
I don't this issue was closed thoughtfully.

**Comment by Yoosk** [comment] 2018-10-07 09:53
After talk with OP on our server he is playing on, issue seems to happen rarely. Im not able to reproduce it in any way, which makes me doubt that there will be any definitive progress in that matter after any given time, but if you will get some clues how to resolve it, please do tell

**Comment by Yoosk** [comment] 2018-11-06 12:29
Since the issue seems abandoned for month, nothing new came out, it is time to close it.

**Closed by Yoosk** 2018-11-06 12:29 UTC
Labels: cannot reproduce, question
