### ISSUE TITLE
Repeatable crash in SP Save and quit then generate a new world

### ISSUE THREAD

**Issue by Glendening** [AllTheMods/ATM3-Remix#235] opened 2019-08-02 04:11 UTC
Repeatable error
ATM3r 1.4.9
Game crashes when generating a new world after quitting a previous world

## Expected Behavior
Not crashing when generating new worlds after playing in a world

## Current Behavior
Game crashes to launcher error log upon generating a new world after quitting a SP world.

## Possible Solution
Noted a tick loop for advancedRocketry in the error log
Disabled advancedRocketry and the crashes caused from the steps noted above stop.

## Steps to Reproduce
1. Load a SP world
2. Save and quit
3. Generate a new world
4. Crash

## Log
https://gist.github.com/Glendening/4f0ce18aa53129627418b04935c9512c

## Detailed Description
Bug may be a conflict with a mod and advancedRocketry or specific to advancedRocketry. Further troubleshooting may be needed.

**Comment by Glendening** [comment] 2019-08-02 04:13
Possible related lines from the log
```

Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at zmaster587.advancedRocketry.dimension.DimensionManager.getTemperature(DimensionManager.java:227)
	at zmaster587.advancedRocketry.dimension.DimensionProperties.getAverageTemp(DimensionProperties.java:1488)
	at zmaster587.advancedRocketry.dimension.DimensionProperties.getAtmosphere(DimensionProperties.java:702)
	at zmaster587.advancedRocketry.event.PlanetEventHandler.CheckSpawn(PlanetEventHandler.java:133)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4299_PlanetEventHandler_CheckSpawn_CheckSpawn.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:224)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.call(Reflector.java:799)
	at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:420)
	at biomesoplenty.common.world.ChunkGeneratorOverworldBOP.func_185931_b(ChunkGeneratorOverworldBOP.java:570)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:186)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by joan-rivers** [comment] 2019-08-10 11:34
wow this pack is broken !

**Comment by Milobe115** [comment] 2019-08-10 16:15
To add to this issue, the problem seems to be caused by an interaction between BoP and Advanced Rocketry, since the problem disappears whenever either BoP or AdvR is disabled/removed.

**Comment by Milobe115** [comment] 2019-08-11 12:13
I have done a bit more research on the subject, and the issue seems to be narrowed down to the Planets.xml file

### First setup

I installed only AdvR and BoP. Same Forge and mods versions as in ATM3-R. 

I could not replicate crash.

### Second setup

I installed AdvR, BoP, Traverse, IEng, OpenComputers, Quark and Twilight Forest. Same versions as always. Copied the `planetDefs.xml` from ATM3-R to my test environment.

I replicated crash consistently, using the method given by Glendening.

### Third setup

Same as the second, with the exception being I did not copy the `planetDefs.xml` file.

I could not replicate crash.

So, I think a potential temporary fix (I've personally implemented it for the time being) is to delete/disable `planetDefs.xml`.

**Comment by Darkere** [comment] 2019-08-28 08:11
The pack has version 160.

**Comment by Milobe115** [comment] 2019-08-28 12:47
I also tested it with build 162, and the problem still occurred.

**Comment by Yamza** [comment] 2019-09-09 15:08
Fixed by mod update.

**Closed by Yamza** 2019-09-09 15:08 UTC
Labels: bug
