### ISSUE TITLE
Can't soft harvest Mystical Agriculture crops.

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM3-Remix#50] opened 2018-09-21 00:50 UTC
This is possible by machine.

**Comment by Glendening** [comment] 2018-09-21 03:39
Some machines also can't soft harvest certain mystical agriculture crops. It might also be related that some mystical agriculture seeds will not plant from certain farming machines. Some added via other mods (Grains of infinity plants for Mysical Agriculture from ender IO as an example) seem to have issues of not being soft harvest-able by the player, not being machine soft harvest-able, and not being machine plant-able where as the basic Mystical plants work just fine for both soft harvest by hand and machine.

**Comment by Chocopuffs** [comment] 2018-09-21 04:43
You can use cyclic harvesters. But the main issue is you can't fertilise then right click to harvest. I have 200k mystical ag fert, but don't use it because I still need to wait for my harvester to harvest.

**Comment by Yoosk** [comment] 2018-09-23 07:46
Duplicate of https://github.com/AllTheMods/ATM3-Remix/issues/18

**Closed by Yoosk** 2018-09-23 07:46 UTC
Labels: duplicate
